// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVG3S6gEZ3f3Gm8HLt1sV94unZk0CzuvE',
    appId: '1:948925982987:web:2b944cf0c5bc319dcf9a0e',
    messagingSenderId: '948925982987',
    projectId: 'noteapp-2666d',
    authDomain: 'noteapp-2666d.firebaseapp.com',
    storageBucket: 'noteapp-2666d.firebasestorage.app',
    measurementId: 'G-JRFP4VDWK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmwkGpIQ4z-rjAdAGMtvLbzbVgegp9IVc',
    appId: '1:948925982987:android:ecddba8b3b39e983cf9a0e',
    messagingSenderId: '948925982987',
    projectId: 'noteapp-2666d',
    storageBucket: 'noteapp-2666d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVG3S6gEZ3f3Gm8HLt1sV94unZk0CzuvE',
    appId: '1:948925982987:web:cb14f78ef902c24acf9a0e',
    messagingSenderId: '948925982987',
    projectId: 'noteapp-2666d',
    authDomain: 'noteapp-2666d.firebaseapp.com',
    storageBucket: 'noteapp-2666d.firebasestorage.app',
    measurementId: 'G-JCWFM2E5LZ',
  );
}
